// File: ViewModels/SendGridSettingsViewModel.cs
using System;
using System.Threading;
using System.Threading.Tasks;
using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;
using LTKCC.Data;
using LTKCC.Models;

namespace LTKCC.ViewModels;

/// <summary>
/// ViewModel = state + commands for the page.
/// The View binds to these properties.
/// </summary>
public partial class SendGridSettingsViewModel : ObservableObject
{
    private readonly AppDb _db;

    // Ensures InitAsync is only run once, even if multiple callers race (page appearing, etc.)
    private readonly SemaphoreSlim _initLock = new(1, 1);
    private bool _dbReady;

    public SendGridSettingsViewModel(AppDb db)
    {
        _db = db ?? throw new ArgumentNullException(nameof(db));

        // Make sure computed flags are correct with defaults.
        RecalcIsValid();
    }

    /// <summary>
    /// Always ensure tables exist + singleton seed is present before reading/writing.
    /// Safe to call multiple times.
    /// </summary>
    public async Task EnsureDbReadyAsync()
    {
        if (_dbReady) return;

        await _initLock.WaitAsync().ConfigureAwait(false);
        try
        {
            if (_dbReady) return;

            await _db.InitAsync().ConfigureAwait(false);
            _dbReady = true;
        }
        finally
        {
            _initLock.Release();
        }
    }

    // ----- validation recompute triggers (generated by [ObservableProperty]) -----
    partial void OnApiUriChanged(string value) => RecalcIsValid();
    partial void OnApiKeyChanged(string value) => RecalcIsValid();
    partial void OnFromEmailChanged(string value) => RecalcIsValid();

    // KeyName / FromName don't affect IsValid right now, but you can add if you decide they're required.
    // partial void OnKeyNameChanged(string value) => RecalcIsValid();
    // partial void OnFromNameChanged(string value) => RecalcIsValid();

    private void RecalcIsValid()
    {
        // Minimal requirements to allow Save.
        IsValid =
            !string.IsNullOrWhiteSpace(ApiUri) &&
            !string.IsNullOrWhiteSpace(ApiKey) &&
            !string.IsNullOrWhiteSpace(FromEmail);
    }

    // ---- Bindable properties (the UI reads/writes these) ----
    [ObservableProperty] private bool isValid;

    [ObservableProperty] private string apiUri = string.Empty;
    [ObservableProperty] private string keyName = string.Empty;
    [ObservableProperty] private string apiKey = string.Empty;
    [ObservableProperty] private string fromEmail = string.Empty;
    [ObservableProperty] private string fromName = string.Empty;

    [ObservableProperty] private bool isBusy;
    [ObservableProperty] private string statusMessage = string.Empty;

    // ---- Commands (buttons call these) ----

    /// <summary>
    /// Loads settings from DB into the bindable properties.
    /// Call this when the page appears.
    /// </summary>
    [RelayCommand]
    private async Task LoadAsync()
    {
        if (IsBusy) return;

        IsBusy = true;
        StatusMessage = string.Empty;

        try
        {
            await EnsureDbReadyAsync();

            // Expected: decrypted values returned by AppDb.GetSendGridSettingsAsync()
            SendGridSettings s = await _db.GetSendGridSettingsAsync();

            ApiUri    = s.ApiUri    ?? string.Empty;
            KeyName   = s.KeyName   ?? string.Empty;
            ApiKey    = s.ApiKey    ?? string.Empty;
            FromEmail = s.FromEmail ?? string.Empty;
            FromName  = s.FromName  ?? string.Empty;

            RecalcIsValid();
            StatusMessage = "Loaded.";
        }
        catch (Exception ex)
        {
            StatusMessage = $"Load failed: {ex.Message}";
        }
        finally
        {
            IsBusy = false;
        }
    }

    /// <summary>
    /// Saves current UI fields back to DB.
    /// AppDb.SaveSendGridSettingsAsync is responsible for encrypting KeyName + ApiKey.
    /// </summary>
    [RelayCommand]
    private async Task SaveAsync()
    {
        if (IsBusy) return;

        // Validate BEFORE setting busy (cleaner UX)
        var apiUriTrim = (ApiUri ?? string.Empty).Trim();
        if (string.IsNullOrWhiteSpace(apiUriTrim))
        {
            StatusMessage = "API URI is required.";
            return;
        }

        var fromEmailTrim = (FromEmail ?? string.Empty).Trim();
        if (!string.IsNullOrEmpty(fromEmailTrim) &&
            !fromEmailTrim.Contains("@", StringComparison.Ordinal))
        {
            StatusMessage = "From Email doesn't look valid.";
            return;
        }

        // Update validity and enforce required fields
        RecalcIsValid();
        if (!IsValid)
        {
            StatusMessage = "Fill in API URI, API key, and From Email before saving.";
            return;
        }

        IsBusy = true;
        StatusMessage = string.Empty;

        try
        {
            await EnsureDbReadyAsync();

            var s = new SendGridSettings
            {
                Id        = 1, // enforce singleton always
                ApiUri    = apiUriTrim,
                KeyName   = (KeyName   ?? string.Empty).Trim(),
                ApiKey    = (ApiKey    ?? string.Empty).Trim(),
                FromEmail = fromEmailTrim,
                FromName  = (FromName  ?? string.Empty).Trim()
            };

            await _db.SaveSendGridSettingsAsync(s);

            StatusMessage = "Saved.";
        }
        catch (Exception ex)
        {
            StatusMessage = $"Save failed: {ex.Message}";
        }
        finally
        {
            IsBusy = false;
        }
    }

    /// <summary>
    /// Convenience command: clears the API key field in the UI.
    /// (Doesn't save until Save is pressed.)
    /// </summary>
    [RelayCommand]
    private void ClearApiKey()
    {
        ApiKey = string.Empty;
        StatusMessage = "API key cleared (not saved yet).";
    }
}
